#!/bin/sh
#yorkie 2.0.0

# 用 `` 可以将命令的输出结果赋值给变量
# 获取当前提交的 commit msg
commit_msg=`cat $1`

# 获取用户 email
email=`git config user.email`
msg_re="^((feat|fix|docs|style|refactor|test|chore|revert)(\(.+\))?:|Merge) .{1,100}"

if [[ ! $commit_msg =~ $msg_re ]]
then
	echo -e "
    提交信息不符合规范!!!
    请按照:
    
        feat：    |  新功能（feature）
        fix：     |  修补bug
        docs：    |  文档（documentation）
        style：   |  格式（不影响代码运行的变动）
        refactor：|  重构（即不是新增功能，也不是修改bug的代码变动）
        test：    |  增加测试
        chore：   |  构建过程或辅助工具的变动    
        revert：  |  commit 回退

    例：feat: 提交信息"
	# 异常退出
	exit 1
fi